''' Window main form application '''
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_Insert = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Insert.setObjectName("pB_Insert")
        self.horizontalLayout.addWidget(self.pB_Insert)
        self.pB_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Delete.setObjectName("pB_Delete")
        self.horizontalLayout.addWidget(self.pB_Delete)
        self.pB_Update = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Update.setObjectName("pB_Update")
        self.horizontalLayout.addWidget(self.pB_Update)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pB_Find = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Find.setObjectName("pB_Find")
        self.horizontalLayout_2.addWidget(self.pB_Find)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pB_fich_insert = QtWidgets.QPushButton(self.centralwidget)
        self.pB_fich_insert.setObjectName("pB_fich_insert")
        self.horizontalLayout_3.addWidget(self.pB_fich_insert)
        self.pB_fish_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pB_fish_delete.setObjectName("pB_fish_delete")
        self.horizontalLayout_3.addWidget(self.pB_fish_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.verticalLayout.addWidget(self.tableWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDataBase = QtWidgets.QMenu(self.menubar)
        self.menuDataBase.setObjectName("menuDataBase")
        self.menuDictionary = QtWidgets.QMenu(self.menuDataBase)
        self.menuDictionary.setObjectName("menuDictionary")
        self.menuUrer = QtWidgets.QMenu(self.menuDataBase)
        self.menuUrer.setObjectName("menuUrer")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionInsert_item = QtWidgets.QAction(MainWindow)
        self.actionInsert_item.setObjectName("actionInsert_item")
        self.actionDelete_item = QtWidgets.QAction(MainWindow)
        self.actionDelete_item.setObjectName("actionDelete_item")
        self.actionCreate_user = QtWidgets.QAction(MainWindow)
        self.actionCreate_user.setObjectName("actionCreate_user")
        self.actionJson = QtWidgets.QAction(MainWindow)
        self.actionJson.setObjectName("actionJson")
        self.actionColor = QtWidgets.QAction(MainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionAll_user = QtWidgets.QAction(MainWindow)
        self.actionAll_user.setObjectName("actionAll_user")
        self.menuFile.addAction(self.actionQuit)
        self.menuDictionary.addAction(self.actionColor)
        self.menuUrer.addAction(self.actionCreate_user)
        self.menuUrer.addAction(self.actionAll_user)
        self.menuDataBase.addAction(self.menuUrer.menuAction())
        self.menuDataBase.addSeparator()
        self.menuDataBase.addSeparator()
        self.menuDataBase.addAction(self.actionJson)
        self.menuDataBase.addAction(self.menuDictionary.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDataBase.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_Insert.setText(_translate("MainWindow", "Insert"))
        self.pB_Delete.setText(_translate("MainWindow", "Delete"))
        self.pB_Update.setText(_translate("MainWindow", "Update"))
        self.pB_Find.setText(_translate("MainWindow", "Select"))
        self.tableWidget.setSortingEnabled(True)
        self.pB_fich_insert.setText(_translate("MainWindow", "Add"))
        self.pB_fish_delete.setText(_translate("MainWindow", "Del"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDataBase.setTitle(_translate("MainWindow", "DataBase"))
        self.menuDictionary.setTitle(_translate("MainWindow", "Dictionary"))
        self.menuUrer.setTitle(_translate("MainWindow", "Urer"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionInsert_item.setText(_translate("MainWindow", "Insert item"))
        self.actionDelete_item.setText(_translate("MainWindow", "Delete item"))
        self.actionCreate_user.setText(_translate("MainWindow", "Create user"))
        self.actionJson.setText(_translate("MainWindow", "Json"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionAll_user.setText(_translate("MainWindow", "All user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
